baseURL = 'https://linguistindex.site/'
languageCode = 'en-us'
title = 'Tech Index'
theme = 'PaperMod'

[pagination]
pagerSize = 6

[outputs]
home = ["HTML", "RSS", "SEARCHJSON"]

[outputFormats]
[outputFormats.SEARCHJSON]
mediaType = "application/json"
baseName = "index"
isPlainText = true
notAlternative = true

[taxonomies]
category = 'categories'
tag = 'tags'

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 15
[[menu.main]]
name = "Tutorials"
url = "/tutorials"
weight = 20
[[menu.main]]
name = "Topics"
url = "/categories"
weight = 25
[[menu.main]]
name = "About Us"
url = "/about"
weight = 30
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 40
[[menu.main]]
name = "Search"
url = "/search"
weight = 50

[params]
defaultTheme = "auto"
env = "production"
mainSections = ["posts", "tutorials"]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 100
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]
description = "High-utility tech tutorials and SaaS guides designed to help you master modern software development and digital tools."
author = "Tech Index"

# Home-Info Mode
[params.homeInfoParams]
Title = "Welcome to Tech Index"
Content = "Showing you how to get the most out of technology and solving problems you might face. You'll find tutorials and SaaS guides designed to help you learn modern software development and digital tools."

# AdSense/SEO Features
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowPostNavLinks = true

# Social Proof
[[params.socialIcons]]
name = "x"
url = "https://x.com/@I_am_Hasnii"
[[params.socialIcons]]
name = "github"
url = "https://github.com/TheOnlyHasni"
[[params.socialIcons]]
name = "facebook"
url = "https://facebook.com/61556325603943"
[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/@i.am.hasni"

# Footer Cleanliness
hideFooter = false # We want the footer, but we will override the content
ShowFullTextinRSS = false

[params.assets]
disableHLJS = false

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"
